### ISSUE TITLE
Create map crash

### ISSUE THREAD

**Issue by zc1108aaa** [ddeeddii/DurabilityPlus#2]
[crash-2024-05-09_14.22.24-client.txt](https://github.com/ddeeddii/DurabilityPlus/files/15258481/crash-2024-05-09_14.22.24-client.txt)
111
[latest0.log](https://github.com/ddeeddii/DurabilityPlus/files/15258485/latest0.log)

**Comment by ddeeddii** [comment]
Thanks for the report.
Fixed with 4ac73f51126cacca0582e9ca2af5feb9d26738a0
